### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by Smile8848** [chenjing1294/TinyGUI#1]
压缩图片分辨率过大时会卡死，建议可以关闭预览图。

**Comment by chenjing1294** [comment]
收到，您单次压缩多少张？每张多大？我这边测试下。

**Comment by chenjing1294** [comment]
> 压缩图片过大时会卡，建议关闭预览图。

收到，您单次压缩多少张？每张多大？我这边测试下。

**Comment by Smile8848** [comment]
单次压缩300M 但是图片分辨率很大 目前我没有参考的图了

**Comment by Smile8848** [comment]
批量图片 这里大概100来张 但是10来张也是这个情况
![](https://s3.bmp.ovh/imgs/2022/02/dcf9ad49267efbb5.png)

**Comment by dongnanyanhai** [comment]
我一次大概会压缩二三百张图片，都是1mb以内的，能否取消预览图？

**Comment by chenjing1294** [comment]
这个

> 批量图片 这里大概100来张 但是10来张也是这个情况 ![](https://camo.githubusercontent.com/9ae35f5c2591ccf80751d2483911346b740fa94724b33be564bc9bf01c4d2aa1/68747470733a2f2f73332e626d702e6f76682f696d67732f323032322f30322f646366396164343932363765666262352e706e67)

你可能需要翻墙才能流畅地访问压缩接口，因为TinyPNG的服务器在国外。微信联系：15829710534

**Comment by 0x9394** [comment]
@chenjing1294 大佬，请问批量文件时，是同时上传吗，现在单个图片上传/下载是正常的，2个或以上图片的话就一直卡在上传中了
