### ISSUE TITLE
图片上传错误

### ISSUE THREAD

**Issue by 448016097** [chenjing1294/TinyGUI#2]
上传图片提示 error while connecting:无法访问已释放的对象，对象名:system.net.http.streamcontent

**Comment by zygst** [comment]
实测文件路径有中文会导致这个问题

**Comment by chenjing1294** [comment]
> 上传图片提示 error while connecting:无法访问已释放的对象，对象名:system.net.http.streamcontent

该错误在什么情况下发生，是否可以复现，可以的话麻烦详细描述，这有助于快速定位问题。

**Comment by chenjing1294** [comment]
> 实测文件路径有中文会导致这个问题

是否可复现，我测试了一下，但是没有遇到该问题。

**Comment by 448016097** [comment]
> 
文件安装路径 "D:\Program Files (x86)\TinyGUI\TinyGUI.exe"
win11登录user为中文【丢丢丢】

图片放在桌面时，拖入软件上传后在下载时会有此提示；
将图片移动至D盘根目录，重复操作，下载时依旧有提示

**Comment by 448016097** [comment]
> > 实测文件路径有中文会导致这个问题
> 
> 是否可复现，我测试了一下，但是没有遇到该问题。

文件安装路径 "D:\Program Files (x86)\TinyGUI\TinyGUI.exe"
win11登录user为中文【丢丢丢】

图片放在桌面时，拖入软件上传后在下载时会有此提示；
将图片移动至D盘根目录，重复操作，下载时依旧有提示

**Comment by 448016097** [comment]
> > 实测文件路径有中文会导致这个问题
> 
> 是否可复现，我测试了一下，但是没有遇到该问题。

再次测试后发现，当图片名称为中文时有提示，图片名称为非中文时正常使用，这个应该是问题的核心。

**Comment by chenjing1294** [comment]
> > > 实测文件路径有中文会导致这个问题
> > 
> > 
> > 是否可复现，我测试了一下，但是没有遇到该问题。
> 
> 再次测试后发现，当图片名称为中文时有提示，图片名称为非中文时正常使用，这个应该是问题的核心。

谢谢，我复现了该bug；尽快在下一版本修复

**Comment by chenjing1294** [comment]
此bug已在1.0.5.0版本中修复
