### ISSUE TITLE
Add image resizing option

### ISSUE THREAD

**Issue by yo1995** [chenjing1294/TinyGUI#6]
你好，请问考虑添加一个简单的更改尺寸功能？例如指定长或宽，或指定较长边
谢谢

**Comment by yo1995** [comment]
多张图像目前无法同时上传，只能一张一张传 🤔

**Comment by yo1995** [comment]
如果可以把覆盖选项的逻辑改成将原图移至回收站，而非直接覆盖，感觉更友好一些

**Comment by chenjing1294** [comment]
### v1.0.8.0支持4种调整图像尺寸的策略
1. **scale**：
    按比例缩小图片。您必须提供目标width或height，不能同时提供两者。缩小后的图片会有确定的宽度或者高度。
1. **fit**
    按比例缩小图片，使其适合（fit）给定的尺寸。你必须同时提供width和height。缩小后的图像不会超过这些尺寸中的任何一个。
1. **cover**
    按比例缩小图片，如有必要裁切图片。结果具有准确的给定尺寸。 图片中哪个部分将被裁切是自动决定的。智能算法确定图像中最重要的区域。
1. **thumb**
    一个更先进的缩略图实现，还能检测具有简单背景的裁切图片。图片会被缩小到您提供的width和height的大小。 如果一个图片被检测到独立物体，算法将在必要位置添加更多的背景，或者裁切掉不重要的部分。

**Comment by yo1995** [comment]
赞
